### ISSUE TITLE
[BUG] CI에서 MySQL 접속 실패로 테스트 단계 오류 발생 (`Access denied` 에러)

### ISSUE THREAD

**Issue by jinlee1703** [TEAM-JJINS/cs-algo#93]
## Bug Description

GitHub Actions CI에서 Gradle test 실행 시 MySQL 접속 오류 발생

에러 메시지:

```
Access denied for user 'test_user'@'20.125.216.88' (using password: YES)
```

기존에는 mirromutth/mysql-action@v1.1 사용 시 정상 작동했으나, 최근부터 위 오류로 테스트 실패

## Steps to Reproduce

1. mirromutth/mysql-action@v1.1으로 MySQL 설정
2. ./gradlew test 실행
3. Spring Boot에서 DB 접속 시도
4. Access denied 에러 발생

## Expected Behavior

Spring Boot 애플리케이션이 CI 환경의 MySQL에 정상적으로 접속해야 함

## Current Behavior

MySQL 접속 실패로 test 단계 전체 실패  
EntityManagerFactory 생성 불가로 인한 빌드 중단

## Possible Solution

mirromutth/mysql-action 제거 후 services.mysql로 교체

예시 설정:

```yaml
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    env:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pw
      MYSQL_ROOT_PASSWORD: root_pw
    options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=10

env:
  SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/test_db
  SPRING_DATASOURCE_USERNAME: test_user
  SPRING_DATASOURCE_PASSWORD: test_pw
```

## Additional Context

- 관련 이슈: https://github.com/mirromutth/mysql-action/issues/32  
  - runner와 컨테이너 간 네트워크 이슈로 추정  
  - secrets 값은 정상 설정되어 있음
